### ISSUE TITLE
Changing database schema

### ISSUE THREAD

**Issue by AlexanderGeiger** [D3-AI/Orion#48]
@kveerama and I discussed some changes of the DB schema:

- add name and description fields to `Datarun` collection
- add `Experiment` collection, which consists of multiple `Dataruns`. (We might want to restrict it such that one `Experiment` can only consist of multiple `Dataruns` with same `Dataset`)

The idea is that the first screen a user would see is the `Experiments` overview. If an `Experiment` is clicked, the different `Dataruns` belonging to the `Experiment` are shown. Thus, `Experiments` are a way of structuring multiple `Dataruns.` A `Datarun` consists of a `Dataset` and a `Pipeline.` When a `Datarun` is clicked, the `Dataset` itself and all `Events` and `Comments` belonging to the `Datarun` are displayed.

If anyone has additional thoughts on that, please feel free to comment.

**Comment by kveerama** [comment]
@csala comment: 
About the Experiments: at some point we discussed a slightly different schema, that would be as follows:

- A Dataset is associated with a Satellite and has a collection of Signals
- A Signal is associated with a single CSV file and has a start and a stop.
- An Experiment is related to a Pipeline and a Dataset.
- Dataruns are related to an Experiment and a Signal, which implicitly relates them to a Dataset and a Pipeline.

For this, we should:

- Rename the current Dataset to Signal.
- Remove the satellite_id and signal_set fields from the Signal model.
- Add another Dataset model that is parent to Signal and has the satellite_id field.
- Create the Experiment model and make it related to Dataset and Pipeline.
- Make the Dataruns related to the Experiment.
- Remove the Datarun <-> Pipeline relationship (as it comes through the Experiment).

Can we adapt the changes to this schema?

**Comment by AlexanderGeiger** [comment]
Closed in #58
