### ISSUE TITLE
A problem of the current  DB schema of "Experiment"

### ISSUE THREAD

**Issue by dyuliu** [D3-AI/Orion#62]
### Description

The DB schema of "Experiment" cannot allow retrieving detailed information of the running results, because we don't know which `dataruns` are related to this experiment.

### Solution

**Current schema:**

```python
class Experiment(Document, MongoUtils):
    project = fields.StringField()
    pipeline = fields.ReferenceField(Pipeline)
    dataset = fields.ReferenceField(Dataset)
    created_by = fields.StringField()
```

**Proposed schema:**

```python
class Experiment(Document, MongoUtils):
    project = fields.StringField(required=True)
    pipeline = fields.ReferenceField(Pipeline)
    dataset = fields.ReferenceField(Dataset)
    created_by = fields.StringField()
    name = fields.StringField(required=True)
    events = fields.IntField(required=True)
    dataruns = fields.ListField(fields.ReferenceField(Datarun))
    start_time = fields.DateTimeField(required=True)
    end_time = fields.DateTimeField()
    status = fields.StringField()
```

The most important attribute is `dataruns`. If we don't store this information, we cannot retrieve any detailed information about this experiment. We can only know which signals are run in this experiment, but know nothing about the running results.

**Comment by csala** [comment]
Hi @dyuliu I would like to discourage this.
This solution make a redundant data model, which will lead to problems.
Also, the additional fields that you are setting should not be made static. They should be computed dynamically, as they might change.

Regarding the dataruns, the way to retrieve them is dataruns is by doing an inverse lookup: you don't have to query the experiment and get the dataruns from there, but rather query the dataruns by filtering on the experiment id:

In mongodb syntax:

```
db.datarun.find({'experiment': <experiment-id>})
```

or, in python syntax:

```
Datarun.find(experiment=<experiment-id>)
```

**Comment by dyuliu** [comment]
> but rather query the dataruns by filtering on the experiment id:

Oh! I just realize that the schema of Datarun has been changed. There is an new attribute "experiment" that can point to the experiment I want to investigate.

Thanks!  @csala 

Now the remaining problem is that shall we add `name` and `creation_time`?

Experiment creation time is somehow important, as I can order all the experiments by creation_time. To obtain the "creation_time", one solution is to filter all the related dataruns and then find the earliest `start_time`. This can compute the time point when the experiment gets to run, but it is not the real `creation_time`. In this regards, I'm not sure whether `creation_time` is still needed.

**Comment by csala** [comment]
Great! I hope filtering from the Datarun covers the needs :-)

Regarding name, we decided to drop it during the PR reviews, because we thought that it didn't seem relevant or required for the Orion workflow. But if it is something needed from a user point of view, it can be added, for sure!

Regarding the creation time, bear in mind that all the models that inherit from the `MongoUtils` class automatically have an `insert_time` field.

**Comment by csala** [comment]
@dyuliu let us know if the `Datarun` filtering and the `insert_time` cover all the needs!

If so, I think this issue can be closed.

**Comment by dyuliu** [comment]
@csala Yes, it covers all the needs.
